{
  "openapi": "3.0.0",
  "info": {
    "title": "Mavka Open API Specification",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:5000",
      "description": "Dev server"
    }
  ],
  "tags": [
    {
      "name": "Authentication",
      "description": "Endpoints related to user authentication"
    },
    {
      "name": "Users",
      "description": "Operations related to managing user data"
    },
    {
      "name": "Chat",
      "description": "Operations related to chat rooms memberships and messages"
    }
  ],
  "paths": {
    "/auth/registration": {
      "post": {
        "summary": "User registration endpoint",
        "description": "This method adds a new user to the database",
        "operationId": "authRegister",
        "tags": ["Authentication"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "pass": {
                    "type": "string"
                  },
                  "first_name": {
                    "type": "string"
                  },
                  "last_name": {
                    "type": "string"
                  }
                },
                "required": [
                  "username",
                  "email",
                  "pass",
                  "first_name",
                  "last_name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful registration",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User registered"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body or missing fields",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string"
                          },
                          "msg": {
                            "type": "string"
                          },
                          "path": {
                            "type": "string"
                          },
                          "location": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "message": "Registration error",
                    "errors": [
                      {
                        "type": "field",
                        "msg": "Password can not be empty",
                        "path": "pass",
                        "location": "body"
                      },
                      {
                        "type": "field",
                        "msg": "Password length is incorrect - must be 4 to 64 symbols",
                        "path": "pass",
                        "location": "body"
                      }
                    ]
                  }
                }
              }
            }
          },
          "409": {
            "description": "Username or email is already used",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "The username is already used"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "User login endpoint",
        "description": "This method returns a token for authentication",
        "operationId": "authLogin",
        "tags": ["Authentication"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "pass": {
                    "type": "string"
                  }
                },
                "required": ["username", "pass"],
                "example": {
                  "username": "gervant",
                  "pass": "1234"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body or missing fields",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string"
                          },
                          "msg": {
                            "type": "string"
                          },
                          "path": {
                            "type": "string"
                          },
                          "location": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "message": "Login error",
                    "errors": [
                      {
                        "type": "field",
                        "msg": "Password can not be empty",
                        "path": "pass",
                        "location": "body"
                      },
                      {
                        "type": "field",
                        "msg": "Password length is incorrect - must be 4 to 64 symbols",
                        "path": "pass",
                        "location": "body"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Incorrect password"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{username}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Get user data",
        "description": "This method returns public information about a user",
        "operationId": "getUser",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "Username of the user to retrieve information",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "string"
                    },
                    "first_name": {
                      "type": "string"
                    },
                    "last_name": {
                      "type": "string"
                    },
                    "wall_id": {
                      "type": "integer"
                    },
                    "avatar_url": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "username": "gervant",
                    "first_name": "Герольд",
                    "last_name": "Ривский",
                    "wall_id": 6,
                    "avatar_url": "https://i.ibb.co/t33h8S6/witcher.jpg"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User with username USERNAME does not exist"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Change user data",
        "description": "This method returns public information about a user",
        "operationId": "editUser",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "Username of the user to retrieve information",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User updated successfully"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body or missing fields",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string"
                          },
                          "msg": {
                            "type": "string"
                          },
                          "path": {
                            "type": "string"
                          },
                          "location": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "message": "Incorrect values error",
                    "errors": [
                      {
                        "type": "field",
                        "msg": "Password can not be empty",
                        "path": "pass",
                        "location": "body"
                      },
                      {
                        "type": "field",
                        "msg": "Password length is incorrect - must be 4 to 64 symbols",
                        "path": "pass",
                        "location": "body"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Can not access private information about another user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Access denied"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email is already used",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "The email is already used"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Delete user",
        "description": "This method deletes user",
        "operationId": "deleteUser",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "Username of the user to delete",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User deleted"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Can not delete another user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Access denied"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/private/{username}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Get user private data",
        "description": "This method returns private information about a user",
        "operationId": "getUserPrivate",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "Username of the user to retrieve information",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "first_name": {
                      "type": "string"
                    },
                    "last_name": {
                      "type": "string"
                    },
                    "wall_id": {
                      "type": "integer"
                    },
                    "avatar_url": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "username": "gervant",
                    "email": "jeraltino@gmail.com",
                    "first_name": "Герольд",
                    "last_name": "Ривский",
                    "wall_id": 6,
                    "avatar_url": "https://i.ibb.co/t33h8S6/witcher.jpg"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Can not access private information about another user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Access denied"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/chat/message/{room_id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Get messages from chat room",
        "description": "This method returns messages from a chat room. By default page is 1 and page size is 10.",
        "operationId": "loadChatMessages",
        "tags": ["Chat"],
        "parameters": [
          {
            "name": "room_id",
            "in": "path",
            "description": "Chat room id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "page number",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "description": "page size",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "username": {
                        "type": "string"
                      },
                      "first_name": {
                        "type": "string"
                      },
                      "last_name": {
                        "type": "string"
                      },
                      "message_text": {
                        "type": "string"
                      },
                      "avatar_url": {
                        "type": "string"
                      },
                      "created_time": {
                        "type": "string"
                      }
                    }
                  },
                  "example": [
                    {
                      "username": "gervant",
                      "first_name": "Герольд",
                      "last_name": "Ривский",
                      "message_text": "холера",
                      "avatar_url": "https://i.ibb.co/t33h8S6/witcher.jpg",
                      "created_time": "2023-12-04T10:04:49.945Z"
                    },
                    {
                      "username": "gervant",
                      "first_name": "Герольд",
                      "last_name": "Ривский",
                      "message_text": "холера",
                      "avatar_url": "https://i.ibb.co/t33h8S6/witcher.jpg",
                      "created_time": "2023-12-04T10:04:49.945Z"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Not a chat member",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Access denied. Not a room member."
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Add new message",
        "description": "This method returns adds new message from a user to a chat room.",
        "operationId": "addChatMessage",
        "tags": ["Chat"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message_text": {
                    "type": "string"
                  }
                },
                "required": ["message_text"]
              }
            }
          }
        },
        "parameters": [
          {
            "name": "room_id",
            "in": "path",
            "description": "Chat room id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Success"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Not a chat member",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Access denied. Not a room member."
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/chat/newroom": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Create new room",
        "description": "This method create a new chat room",
        "operationId": "createChatRoom",
        "tags": ["Chat"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "room_name": {
                    "type": "string"
                  }
                },
                "required": ["room_name"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "room_id": {
                      "type": "integer"
                    }
                  },
                  "example": {
                    "room_id": 45
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body or missing fields",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string"
                          },
                          "msg": {
                            "type": "string"
                          },
                          "path": {
                            "type": "string"
                          },
                          "location": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "message": "Incorrect values error",
                    "errors": [
                      {
                        "type": "field",
                        "msg": "Room name can not be empty",
                        "path": "room_name",
                        "location": "body"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/chat/personal-message/{username}": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Add personal message",
        "description": "This method creates a personal message to a user",
        "operationId": "createPersonalMessage",
        "tags": ["Chat"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "string"
                  }
                },
                "required": ["text"]
              }
            }
          }
        },
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "username of a user whom to send the message",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Success"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body or missing fields",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string"
                          },
                          "msg": {
                            "type": "string"
                          },
                          "path": {
                            "type": "string"
                          },
                          "location": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "message": "Incorrect values error",
                    "errors": [
                      {
                        "type": "field",
                        "msg": "Mesage text can not be empty",
                        "path": "message_text",
                        "location": "body"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Not authorized"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}
